services:
  nginx-service:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/usr/share/nginx/html
      - /etc/letsencrypt/live/fuelstack.icu/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/fuelstack.icu/privkey.pem:/etc/ssl/private/privkey.pem:ro
    restart: always
    networks:
      - common_network
networks:
  common_network:
    external: true